spring:
  r2dbc:
    url: r2dbc:h2:mem:///db?options=DB_CLOSE_DELAY=-1
    username: sa
    password:
    h2:
      console:
        enabled: true
springdoc:
  webjars:
    prefix: ""
server:
  error:
    include-stacktrace: on_param