CREATE TABLE IF NOT EXISTS cliente (
	id SERIAL,
    cpf VARCHAR(20) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    cep VARCHAR(8) NOT NULL,
    PRIMARY KEY (id)
);